// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package db

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestQueries_CreateAccount(t *testing.T) {
	ctx := context.Background()
	arg := CreateAccountParams{
		Owner:    "test_owner",
		Balance:  1000,
		Currency: "USD",
	}
	q := testQueries
	err := q.CreateAccount(ctx, arg)
	assert.NoError(t, err)
}
