// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package db

import (
	"context"
	"testing"

	"github.com/PHANTOM-HAWK/golang-practise/db/util"
	"github.com/stretchr/testify/assert"
)

func CreateAccount(t *testing.T) Account {
	ctx := context.Background()
	arg := CreateAccountParams{
		Owner:    util.RandomString(),
		Balance:  int64(util.RandomAmount()),
		Currency: util.RandomCurrency(),
	}
	q := testQueries
	account, _ := q.CreateAccount(ctx, arg)
	return account
}

func TestQueries_CreateAccount(t *testing.T) {
	ctx := context.Background()
	arg := CreateAccountParams{
		Owner:    util.RandomString(),
		Balance:  int64(util.RandomAmount()),
		Currency: util.RandomCurrency(),
	}
	q := testQueries
	account, err := q.CreateAccount(ctx, arg)
	assert.Equal(t, account.Balance, arg.Balance)
	assert.Equal(t, arg.Owner, account.Owner)
	assert.NoError(t, err)

}
